name: YingYongBao

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3.3.0
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v3.2.1
        with:
          packages: 'platform-tools platforms;android-34 build-tools;34.0.0'
      
      - name: Output build-tools path and add to PATH
        run: |
          ls -la ${ANDROID_SDK_ROOT}/build-tools/34.0.0
          echo "${ANDROID_SDK_ROOT}/build-tools/34.0.0" >> $GITHUB_PATH

      - name: Copy files
        run: |
          cp -r sh/* ./

      - name: Make patch_yingyongbao.sh executable
        run: chmod +x patch_yingyongbao.sh

      - name: Make download.sh executable
        run: chmod +x download.sh

      - name: Download required files
        run: ./download.sh

      - name: Build APK
        run: ./patch_yingyongbao.sh

      - name: Make zipalign_sign.sh executable
        run: chmod +x zipalign_sign.sh

      - name: Zipalign and Sign Android release
        run: ./zipalign_sign.sh

      - name: Create GitHub Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "YingYongBao"
          draft: true
          title: " ${{ env.PERSEUS_VERSION }}"
          files: |
            build/*.apk
